
#
##########

{% set noOfNodes = noOfNodes | int %}

version: '3.6'

services:
  notary:
    image: corda/corda-zulu-java1.8-4.4
    container_name: notary
    ports:
      - "10003:10201"
    volumes:
      - ./notary/node.conf:/etc/corda/node.conf
      - ./notary/certificates:/opt/corda/certificates
      - ./notary/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps
      - ./shared/node-infos:/opt/corda/additional-node-infos
      - ./shared/network-parameters:/opt/corda/network-parameters


{% for n in range(noOfNodes) %}
  party{{n}}:
    image: corda/corda-zulu-java1.8-4.4
    container_name: party{{n}}
    expose:
      - 10201
      - 2222
    volumes:
      - ./party{{n}}/node.conf:/etc/corda/node.conf
      - ./party{{n}}/certificates:/opt/corda/certificates
      - ./party{{n}}/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps
      - ./shared/node-infos:/opt/corda/additional-node-infos
      - ./shared/network-parameters:/opt/corda/network-parameters
{% endfor %}
