version: '3.0'  

services:
  notary: 
    image: corda/corda-zulu-java1.8-4.4
    container_name: notary 
    ports:
      - "10003:10201"
    volumes:
      - ./notary/node.conf:/etc/corda/node.conf
      - ./notary/certificates:/opt/corda/certificates
      - ./notary/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps
      - ./shared/node-infos:/opt/corda/additional-node-infos
      - ./shared/network-parameters:/opt/corda/network-parameters

  partya: 
    image: corda/corda-zulu-java1.8-4.4
    container_name: partya
    ports:
      - "10006:10201"
      - "2222:2222"
    volumes:
      - ./partya/node.conf:/etc/corda/node.conf
      - ./partya/certificates:/opt/corda/certificates
      - ./partya/persistence:/opt/corda/persistence
      - ./shared/cordapps:/opt/corda/cordapps      
      - ./shared/node-infos:/opt/corda/additional-node-infos
      - ./shared/network-parameters:/opt/corda/network-parameters
